{% set name = "jupyter-flex" %}
{% set version = "0.6.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter-flex-{{ version }}.tar.gz
  sha256: 727856f0c49ca0145899267f01ff493a7886dd6a73b90ff16bc404f02c34e93c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - nbconvert >=6.0.7,<7
    - voila >=0.2.0,<0.3

test:
  imports:
    - jupyter_flex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/danielfrg/jupyter-flex
  summary: Easily create Dashboards using Jupyter Notebooks
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
